apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
  namespace: kubeflow
data:
  executor: |
    imagePullPolicy: IfNotPresent
    image: quay.io/argoproj/argoexec:v3.4.16
